// Generated by CoffeeScript 1.12.6

/**
 * Dictionary - примітивна реалізація одноіменного класу в ActionScript 3.0
 * По суті це така ж хеш-колекція, як нативний Object, але значення її ключів не приводяться до строкового типу
 */

(function() {
  var Dictionary;

  Dictionary = (function() {
    Dictionary.prototype._keys = null;

    Dictionary.prototype._values = null;

    function Dictionary() {
      this._keys = [];
      this._values = [];
    }

    Dictionary.prototype.set = function(key, value) {
      var idx;
      idx = this._keys.indexOf(key);
      if (idx === -1) {
        idx = this._keys.length;
      }
      this._keys[idx] = key;
      return this._values[idx] = value;
    };

    Dictionary.prototype.get = function(key) {
      var idx;
      idx = this._keys.indexOf(key);
      if (idx !== -1) {
        return this._values[idx];
      } else {
        return void 0;
      }
    };

    Dictionary.prototype.has = function(key) {
      return -1 !== this._keys.indexOf(key);
    };

    Dictionary.prototype.key = function(value) {
      var idx;
      idx = this._values[value];
      if (idx !== -1) {
        return this._keys[idx];
      } else {
        return void 0;
      }
    };

    Dictionary.prototype.del = function(key) {
      var idx;
      idx = this._keys.indexOf(key);
      if (idx !== -1) {
        this._keys.splice(idx, 1);
        return this._values.splice(idx, 1);
      }
    };

    Dictionary.prototype.keys = function(safe) {
      if (safe == null) {
        safe = true;
      }
      if (safe) {
        return this._keys.slice();
      } else {
        return this._keys;
      }
    };

    Dictionary.prototype.values = function(safe) {
      if (safe == null) {
        safe = true;
      }
      if (safe) {
        return this._values.slice();
      } else {
        return this._values;
      }
    };

    return Dictionary;

  })();

  window.Dictionary = Dictionary;

}).call(this);
