// Generated by CoffeeScript 1.12.6
(function() {
  $.post = function(url, success) {
    var amount;
    amount = Math.round(200 * Math.random());
    return setTimeout(function() {
      return success(amount);
    }, 1e3);
  };

}).call(this);
