// Generated by CoffeeScript 1.12.6

/**
 * Заглушка, що містить пародію на $.post(...)
 * На відміну від попередньої версії, дана функція реагує на параметр `url`,
 * створюючи для унікальних адрес окремий эмулятор сервера
 */

(function() {
  var jQWERTY;

  jQWERTY = (function() {
    function jQWERTY() {}

    jQWERTY._STUBS_ = {};

    jQWERTY.post = function(url, success) {
      var stub;
      stub = this._STUBS_[url] = this._STUBS_[url] || new ServerEmulator(url);
      return setTimeout(function() {
        return success(stub.usersAmount);
      }, stub._responseTime);
    };

    return jQWERTY;

  })();

  window.jQWERTY = jQWERTY;

}).call(this);
