// Generated by CoffeeScript 1.12.6
(function() {
  var ServerEmulator, jQWERTY,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  jQWERTY = (function() {
    function jQWERTY() {}

    jQWERTY.post = function(url, success) {
      setTimeout(function() {
        success(serverEmulator.usersAmount);
      }, Math.random(333));
    };

    return jQWERTY;

  })();

  ServerEmulator = (function() {
    function ServerEmulator() {
      this.update = bind(this.update, this);
    }

    ServerEmulator.prototype._updRate = 300;

    ServerEmulator.prototype._updPtr = -1;

    ServerEmulator.prototype._maxIncome = 20;

    ServerEmulator.prototype._maxOutcome = 20;

    ServerEmulator.prototype._changeChance = 0.75;

    ServerEmulator.prototype.usersAmount = 0;

    ServerEmulator.prototype.run = function() {
      this._updPtr = setInterval((function(_this) {
        return function() {
          if (Math.random() < _this._changeChance) {
            return _this.update();
          }
        };
      })(this), this._updRate);
    };

    ServerEmulator.prototype.die = function() {
      clearInterval(this._updPtr);
    };

    ServerEmulator.prototype.update = function() {
      var change, income, outcome;
      income = Math.random() * this._maxIncome;
      outcome = Math.random() * this._maxOutcome;
      change = Math.round(income - outcome);
      this.usersAmount += change;
      if (this.usersAmount < 0) {
        this.usersAmount = 0;
      }
    };

    return ServerEmulator;

  })();

  window.jQWERTY = jQWERTY;

  window.serverEmulator = new ServerEmulator();

}).call(this);
